### PR TITLE
Convert to System.Text.Json

### PR DESCRIPTION
**Pull request by steveoh**
refs #148

### CODE REVIEW

**Comment by steveoh** [comment]
@xfischer, @xperiandri, and @matt-lethargic I'd love to get some early participation with this

**Comment by steveoh** [comment]
Someone is going to have to refactor all of the tests since they are depending on json.net serialization instead of static strings which isn't awesome.

**Comment by steveoh** [comment]
Can we use c# 9 in this project? I wouldn't think it would matter much to users but I figured I'd ask.

**Comment by matt-lethargic** [comment]
Yep

**Comment by steveoh** [comment]
if we need to rewrite all the tests, do you want to continue to use nunit or would xunit be more attractive?

**Comment by steveoh** [comment]
tests are now running

```
Failed:    62, Passed:    55, Skipped:     0, Total:   117, Duration: 379 ms
```

**Comment by steveoh** [comment]
I never got an invite by the way. Is anyone going to have some time to work on this with me?

**Comment by steveoh** [comment]
how is this week looking for anyones participation?

**Comment by xfischer** [comment]
Hi @steveoh, thank you for contributing. You're not alone :)
I'll try to look at your commits this week. I'm very busy, but you really deserve our support on this, so thank you, again.

**Comment by steveoh** [comment]
Thanks! I'm a little blocked right now by an over/under read error on the utf8jsonreader for Features. Everything looks normal so I must be missing something not very obvious. Maybe the RC1 STJ will think differently otherwise I'm going to need a bit more help to troubleshoot it.

**Comment by matt-lethargic** [comment]
@steveoh Sorry for not replying sooner, I've been on holiday with family and had strict instructions to not touch computer! I'm just catching up with things, but will be here to help. I want to get this done as well, just a matter of getting some time on it

**Comment by steveoh** [comment]
> @steveoh Sorry for not replying sooner, I've been on holiday with family and had strict instructions to not touch computer! I'm just catching up with things, but will be here to help. I want to get this done as well, just a matter of getting some time on it

Welcome back! I'm in the spatial community slack if you wanted to chat about what i've done and why.

**Comment by steveoh** [comment]
99 tests passing only 10 left to go. I hope you are ok with my implementation. Please tell me that you have at least glanced at it already?

**Comment by steveoh** [comment]
all the tests are now passing. do with it what you want

**Comment by steveoh** [comment]
I think i'm going to use https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON/blob/develop/src/NetTopologySuite.IO.GeoJSON4STJ as their implementation looks much nicer than what I did. You might reference this if you ever get around to it. 

FYI, I will delete my fork in the coming days.

**Comment by xfischer** [comment]
@steveoh I'm sorry the story ends like this. We're just two (three with you) maintaining this repo. I am *very* busy lately so that I couldn't support all the great work you were doing. Sorry about that.

**Pull request closed without merging**
