### PR TITLE
GeoJSON.Net update to .Net Core

### PR DESCRIPTION
**Pull request by gbmarfo**
Hello, does anyone have an update of this great library to .Net Core. A response will be greatly appreciated.

Email: gbmarfo@gmail.com

### CODE REVIEW

**Comment by matt-lethargic** [comment]
Hi, the project builds in .net 3.5, .net 4.0 .net 4.5, .net standard 1.0 and .net standard 1.1. we should have .net core covered!! We're using Visual Studio 2017 that lets you work with multi-targeted frameworks a lot better, but I understand that not everyone has access to this yet. 

All of this should be in the current release on Nuget and I will hopefully be creating a new alpha release soon as some work has been done lately.

Is there a specific issue that you're having with the current release and .net core?

**Comment by matt-lethargic** [comment]
Closing as no reply from @gbmarfo

**Comment by gbmarfo** [comment]
Thanks matt and sorry for the delay in reply.

I got it installed successfully now in .net core. My issue now is how to
implement it with entity framework core.

Any ideas?

Thanks,
Godwin

**Comment by matt-lethargic** [comment]
I don't have that much knowledge when it comes to Geo and EF. I know there is a https://github.com/gksource/GeoJSON.Net.Contrib.EF project, but this has nothing to do with us. 

In #93 we discovered that it was old and in need of some updating. PErhaps take a look at that.

Hope this helps

**Comment by matt-lethargic** [comment]
I don't have much experience of EF in regards to this stuff. 

I know there is another project for a Contrib library as discussed [here](https://github.com/GeoJSON-Net/GeoJSON.Net/issues/92)

**Pull request closed without merging**
