### PR TITLE
Submitted fix for Issue #81 that I opened, LineString will work when built with objects that implement IPosition

### PR DESCRIPTION
**Pull request by GeekActual**
My Second attempt to fix issue #81 with LineString.IsClosed() failing when objects implementing IPosition are passed for the constructor.

### CODE REVIEW

**Comment by GeekActual** [comment]
We are actively working on a set of projects that will use GeoJSON. I had implemented in our in-house library about a 1/3rd of the work you had done, However I like you implementation better. 

We will be using your version (instead of mine) and I didn't see any reason why we should also contribute to those things we need to fix as well.

**Comment by matt-lethargic** [comment]
Thanks for the pull request, just checked it out and you have found a good little thing.
There is in fact no need to cast the coordinate using the as operator as it is already an IPosition, you could write this like
```
    public bool IsClosed()
        {
            var firstCoordinate = Coordinates[0];
            if (firstCoordinate != null)
            {
                var lastCoordinate = Coordinates[Coordinates.Count - 1];

                return firstCoordinate.Longitude.Equals(lastCoordinate.Longitude)
                       && firstCoordinate.Latitude.Equals(lastCoordinate.Latitude)
                       && firstCoordinate.Altitude.Equals(lastCoordinate.Altitude);
            }

            return Coordinates[0].Equals(Coordinates[Coordinates.Count - 1]);
        }
```

and thinking about it, it could even be refactored more to:

  ```
  public bool IsClosed()
        {
            var firstCoordinate = Coordinates[0];
            var lastCoordinate = Coordinates[Coordinates.Count - 1];

            return firstCoordinate.Longitude.Equals(lastCoordinate.Longitude)
                   && firstCoordinate.Latitude.Equals(lastCoordinate.Latitude)
                   && firstCoordinate.Altitude.Equals(lastCoordinate.Altitude);
        }
```

as the check for null is only there because of the `as` operator

**Comment by matt-lethargic** [comment]
Have just implemented the changes I described, closing PR :-)

**Comment by GeekActual** [comment]
Thanks for the change Matt, I'll pull down your master branch and use that in our stuff. Since I'm a new "contributor" I wanted to make as few changes as possible, just so you could more easily see what I was doing and consider them carefully for incorporation.

(Love your user name btw).

Matthew

**Pull request closed without merging**
