### PR TITLE
Migrated project to support dotnet-core

### PR DESCRIPTION
**Pull request by hanssens**
This PR should fix issue #54 ("Porting the library to dnxcore50"). 

Basically, what's done:

* Converted only the project files to dotnet-core
* Actual changed code is mostly in the Test project
* All other files still have their original history intact (so the blame button will still work)
* It is still backwards compatible with .net 4.5.1 (and higher)
* All tests are green

Hope you like it ;)
/cc @jbattermann

### CODE REVIEW

**Comment by jbattermann** [comment]
Woohoo - nice one Juliën / @hanssens! I'll have a closer look the next couple of days and probably pull it in into a separate branch first (making sure appveyor and ci / nuget publishing etc all work) but thanks a lot already! 👍

**Comment by hanssens** [comment]
@jbattermann just curious, any chance to have a look at it yet?

**Comment by hanssens** [comment]
Awesome, thanks! 👍

**Comment by jbattermann** [comment]
Good evening @hanssens! I am still getting used to fiddling with the dotnet tooling and project.json etc notation.. and how to properly adjust the build at Appveyor.. so it might take a bit until the updated Nuget package is actually pushed, but thanks! 👍 

I'll post a quick update here when the NuGet Package is pushed.

Cheers!

**Comment by jbattermann** [comment]
Oh my.. this will take a tad longer than expected - the whole CI bulding, testing & deployment / nuget publishing via Appveyor does not work 'just like that' after switching over to dotnet core .. doing a bit more fiddling..

**Comment by hanssens** [comment]
@jbattermann Anything I can do to assist? Would love to help...

**Pull request merged**
