### PR TITLE
Feature/support system text json

### PR DESCRIPTION
**Pull request by MartinCarpentier**
This merge request adds:

- Conversion of the core serialization package from Newtonsoft to System.Text.Json
- Added github actions, to test the build pipeline
- The code comitted here only support .net core 3.1 and onwards.

Further information:
The code is not complete, but i made this merge request to give some visibility on the work, and maybe spark some discussions.

I have tested the performance of the serialization using benchmarkdotnet, and it's between 300%-400% better than with newtonsoft. Furthermore the memory footprint is alot smaller.

**Result**
``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19042.1348 (20H2/October2020Update)
AMD Ryzen 7 3800X, 1 CPU, 16 logical and 8 physical cores
.NET SDK=6.0.100
  [Host]     : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
  DefaultJob : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT


```
|                     Method |      N |       Mean |     Error |    StdDev |      Gen 0 |     Gen 1 |    Gen 2 |  Allocated |
|--------------------------- |------- |-----------:|----------:|----------:|-----------:|----------:|---------:|-----------:|
| **SerializeNewtonsoftGeoJson** |   **1000** |   **5.258 ms** | **0.0217 ms** | **0.0203 ms** |   **195.3125** |  **195.3125** | **195.3125** |   **2,167 KB** |
| SerializeSystemTextGeoJson |   1000 |   1.528 ms | 0.0044 ms | 0.0037 ms |    70.3125 |   70.3125 |  70.3125 |     360 KB |
| **SerializeNewtonsoftGeoJson** |  **10000** |  **57.959 ms** | **1.0079 ms** | **0.9428 ms** |  **2111.1111** | **1222.2222** | **333.3333** |  **21,638 KB** |
| SerializeSystemTextGeoJson |  10000 |  16.148 ms | 0.0556 ms | 0.0464 ms |   312.5000 |  156.2500 | 156.2500 |   3,595 KB |
| **SerializeNewtonsoftGeoJson** | **100000** | **577.267 ms** | **2.4003 ms** | **2.1278 ms** | **18000.0000** | **6000.0000** |        **-** | **216,329 KB** |
| SerializeSystemTextGeoJson | 100000 | 175.791 ms | 1.6414 ms | 1.3707 ms |  1000.0000 |         - |        - |  35,940 KB |

### CODE REVIEW

**Comment by matt-lethargic** [comment]
Hi @MartinCarpentier and thank you so much for making this PR.

Using `System.Text.Json` has been on my mind for this library for some time now, but unfortunately time has been against me as you can tell by the lack of movement.

One of the main goals initially for this lib was to use Json.Net (Newtonsoft), hence the name GeoJson.Net! I personally think that we should continue to support that. To that end I had been thinking about how we could support both. Maybe something along the lines of a core package `GeoJson.Net` and then sub packages `GeoJson.Net.Newtonsoft` and `GeoJson.Net.Text` or something with better names. 

Have you thought about this? I'm move than willing to help develop something like this with you. Thoughts?

Also great work on the benchmarking, this is something I've always wanted to have in the CI process so we could see if we'd made a change for the worse.

**Comment by MartinCarpentier** [comment]
No problem at all. 
I am using this library at my workplace, and I thought it could be a fun project to convert it, and then test if it would have a performance benefit.

That sounds like good thoughts, and I would like being a part setting that up.

Hmmm.. Moving this into 3 project could make sense.
But couldn't we just aswell fork this repository into a new one called GeoJson.Text and leave this as the library with support for Newtonsoft?

I don't know if the complexity of having a core project shared between a Newtonsoft and a System.Text.Json project would be worth the effort, since this is a rather small library.

The only thing they share is the models, and most of the serialization attributes is bound directly to these models.

But these are just my quick thoughts.

**Comment by matt-lethargic** [comment]
I like the idea of having two repositories, as you said the only thing that is duplicated are the models and you can't really share them as they have attributes related to either Newtonsoft or .Text.Json.

Leave it with me and I'll get something setup so we can get .Text.Json up and running 👍

**Comment by matt-lethargic** [comment]
https://github.com/GeoJSON-Net/GeoJSON.Text

^ Rough copy with Newtonsoft taken out.

**Comment by MartinCarpentier** [comment]
Perfect!

I will fork it, and update it with the code i made?

**Comment by matt-lethargic** [comment]
Closing this PR as Martin has built GeoJSON.Text. Good work 👍

**Pull request closed without merging**
