### PR TITLE
add strong name

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by xfischer** [comment]
Thanks @SimonCropp. If I remember well, creating the key file is requiring a password. Can you share it with us via our Gitter (sent you an invite) ?

**Comment by SimonCropp** [comment]
i did a non password key

**Comment by xfischer** [comment]
OK I didn't knew about that. Thanks @SimonCropp !

**Comment by SimonCropp** [comment]
since

> Do not rely on strong names for security. They provide a unique identity only.

https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

there is no real need for a password

**Comment by xfischer** [comment]
Let's Nugetish now !

**Comment by xfischer** [comment]
GeoJson.Net 1.1.73 published ! Thanks

**Pull request merged**
